- hosts: localhost
  tasks:
    - name: Create a github Repo
      github_repo:
        github_auth_key: "hemant"
        name: "Hello-World"
        description: "This is your first repository"
        private: yes
        has_issues: no
        has_wiki: no
        has_downloads: no
        state: present
      register: result

    - debug: var=result
