- hosts: apic
  vars:
    creds:
        username: "{{ user }}"
        password: "{{ passwd }}"
        host: "{{ inventory_hostname }}"
  tasks:
    - name: Create tenant test
      hk_create_tenantv3:
        action: "post"
        tenant_name: "{{ item }}"
        state: "present"
        creds: "{{ creds }}"
      with_items:
        - 'Rahul5'

      register: result

    - debug: var=result
